config/routes.rb
Instacoo::Application.routes.draw do
  devise_for :users
  get "homepage/index"

  root "homepage#index"

    resources :photos
    resources :tags

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }

  has_and_belongs_to_many :tags

  belongs_to :user 

  validates :description, length: 2..255
  validates :image, attachment_presence: {message: 'required'}

  def tag_list
    ''
  end

  def tag_list=(list)
    list.split(' ').map do |text|
      self.tags << Tag.find_or_create_by(name: text)
    end
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :photos

end

app/models/user.rb
class User < ActiveRecord::Base

  has_attached_file :image, styles: { thumb: "100x100>" }
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
    @photos = Photo.all
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_action :authenticate_user!, except: :index

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def edit 
    @photo = current_user.photos.find params[:id]
  end

  def update
    @photo = Photo.find params[:id]
    @photo.update(permitted_params)

    flash[:notice] = 'Photo updated'
    redirect_to '/'
  end

  def destroy 
    @photo = current_user.photos.find params[:id]
    @photo.destroy
    redirect_to '/'
  end

  def create
    @photo = current_user.photos.new(permitted_params)


    if @photo.save
      flash[:notice] = 'Photo added'
      WebsocketRails[:photos].trigger('new_photo', 
              {description: @photo.description, image_url: @photo.image.url(:medium), tags: @photo.tags})
          
      redirect_to photos_path
    else
      render 'new'
    end
  end

  def permitted_params
    params[:photo].permit(:image, :description, :title, :tag_list) #, :tag_list)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find params[:id]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def all_tags photo
    tags = photo.tags.map do |tag|
      link_to tag.name, tag_path(tag)
    end

    tags.join(', ').html_safe
  end

end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/homepage/index.html.haml
/ %header
/   %nav
/     %a
/       %i
/     %a
/       = link_to 'Sign Up', new_user_registration_path
/     %a
/       = link_to 'Sign In', new_user_session_path
/     %a
/       = link_to 'Upload', new_photo_path
/     %a
/       Instacoo
/     %a
/       Username
/     %a
/       View Profile
/     %a
/       Edit Profile
/     %a
/       Badges
/     %a
/       = link_to 'Log Out', destroy_user_session_path, method: :delete

/ %section{class: 'main'}
%div{ class: 'photos' }

  = render 'photos/pictures'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Instacoo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Instacoo</a>
        <div class="nav-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/photos/_pictures.html.haml
.col-md-4
  - @photos.each do |photo|
    %section{ class: 'picture' }
      %img{ src: photo.image.url(:medium), class: 'uploaded-pic' }
      %p
        = photo.description
      %h3
        = photo.user.email if photo.user
        = link_to 'Edit', edit_photo_path(photo) if photo.user == current_user
        = link_to 'Delete', photo_path(photo), method: :delete
      .tags
        = all_tags(photo)
      

app/views/photos/edit.html.haml
= if @photo.errors.any? 
  .error_explanation
    %h2
      = pluralize(@photo.errors.count, "error") 
      prohibited this photo from being saved

      - @photo.errors.full_messages.each do |msg|
        %li 
          = msg 

= form_for @photo, html: { multipart: true } do |f|

  = f.label :description
  = f.text_field :description

  = f.label :image 
  = f.file_field :image

  = f.submit 'Add Image'

app/views/photos/index.html.haml
.photos
  = render 'pictures'

app/views/photos/new.html.haml
= if @photo.errors.any? 
  .error_explanation
    %h2
      = pluralize(@photo.errors.count, "error") 
      prohibited this photo from being saved

      - @photo.errors.full_messages.each do |msg|
        %li 
          = msg 

= form_for @photo, html: { multipart: true } do |f|

  = f.label :description
  = f.text_field :description

  = f.label :tag_list
  = f.text_field :tag_list

  = f.label :image 
  = f.file_field :image

  = f.submit 'Add Image'

app/views/tags/show.html.haml
%h3
  = @tag.name

- @tag.photos.each do |photo|
  %img{ src: photo.image.url(:medium), class: 'uploaded-pic' }
  = all_tags(photo)